@extends('admin.layouts.v2')
@section('page_title', __('student_follow_up_admin.view_student'))
@section('page_subtitle', $year->name)
@section('style') @include('admin.student_follow_ups._styles') @endsection
@section('content')
<div class="sfu-admin"><div class="v2-card sfu-shell">
<div class="sfu-intro"><div><h3>{{ trim($student->first_name.' '.$student->last_name) }}</h3><p>{{ optional($placement)->class_name }} / {{ optional($placement)->room_name }} | {{ __('student_follow_up_admin.academic_year') }}: {{ $year->name }} | {{ __('student_follow_up_admin.month') }}: {{ $month }}</p></div><div class="sfu-actions"><a class="btn btn-primary" target="_blank" href="{{ route('admin.student_follow_ups.student.report',['student'=>$student->id,'month'=>$month]) }}">{{ __('student_follow_up_admin.print_student_report') }}</a><a class="btn btn-outline-secondary" href="{{ route('admin.student_follow_ups.students',['month'=>$month]) }}">{{ __('student_follow_up_admin.back') }}</a></div></div>
<div class="sfu-summary"><div class="sfu-stat"><span>{{ __('student_follow_up_admin.subjects_with_observations') }}</span><strong>{{ $followUps->getCollection()->pluck('lesson_id')->unique()->count() }}</strong></div><div class="sfu-stat"><span>{{ __('student_follow_up_admin.teachers_with_observations') }}</span><strong>{{ $followUps->getCollection()->pluck('teacher_id')->unique()->count() }}</strong></div><div class="sfu-stat"><span>{{ __('student_follow_up_admin.observations') }}</span><strong>{{ $followUps->total() }}</strong></div></div>
@forelse($followUps->getCollection()->groupBy('lesson_id') as $subjectRows)<section class="sfu-subject-group"><h4>{{ optional($subjectRows->first()->lesson)->name }}</h4>@foreach($subjectRows->groupBy('teacher_id') as $teacherRows)<div class="sfu-observation"><div class="sfu-observation-head"><div><strong>{{ optional($teacherRows->first()->teacher)->first_name }} {{ optional($teacherRows->first()->teacher)->last_name }}</strong><span class="sfu-meta">{{ optional($teacherRows->first()->classRoom)->name }} / {{ optional($teacherRows->first()->room)->name }}</span></div></div>@foreach($teacherRows as $followUp)<div class="sfu-note"><strong>{{ optional($followUp->observed_at)->timezone('Asia/Damascus')->format('Y-m-d H:i') }}</strong> | {{ $followUp->compliance_half==1 ? __('student_follow_up_admin.first_half') : __('student_follow_up_admin.second_half') }} | {{ $followUp->level ? __('student_follow_up.levels.'.$followUp->level) : '—' }} @if($followUp->edited_at)<span class="sfu-badge in_progress">{{ __('student_follow_up_admin.edited') }}</span>@endif<br>{{ $followUp->note ?: __('student_follow_up_admin.no_note') }}</div>@endforeach</div>@endforeach</section>@empty<div class="sfu-empty"><h4>{{ __('student_follow_up_admin.empty_title') }}</h4><p>{{ __('student_follow_up_admin.empty_text') }}</p></div>@endforelse
<div class="mt-3">{{ $followUps->links() }}</div></div></div>
@endsection
