@extends('admin.layouts.v2')
@section('page_title', __('student_follow_up_admin.view_teacher'))
@section('page_subtitle', $year->name)
@section('style') @include('admin.student_follow_ups._styles') @endsection
@section('content')
<div class="sfu-admin"><div class="v2-card sfu-shell">
    <div class="sfu-intro"><div><h3>{{ trim($teacher->first_name.' '.$teacher->last_name) }}</h3><p>{{ __('student_follow_up_admin.month') }}: {{ $month }} | {{ __('student_follow_up_admin.academic_year') }}: {{ $year->name }}</p></div><div class="sfu-actions"><a class="btn btn-outline-primary" target="_blank" href="{{ route('admin.student_follow_ups.teacher.compliance_report', array_merge(request()->query(),['teacher'=>$teacher->id])) }}">{{ __('student_follow_up_admin.print_compliance') }}</a><a class="btn btn-outline-primary" target="_blank" href="{{ route('admin.student_follow_ups.teacher.evaluations_report', array_merge(request()->query(),['teacher'=>$teacher->id])) }}">{{ __('student_follow_up_admin.print_evaluations') }}</a><a class="btn btn-outline-secondary" href="{{ route('admin.student_follow_ups.teachers',['month'=>$month]) }}">{{ __('student_follow_up_admin.back') }}</a></div></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if(isset($errors) && $errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="sfu-summary"><div class="sfu-stat"><span>{{ __('student_follow_up_admin.applicable_contexts') }}</span><strong>{{ $teacherSummary['contexts'] }}</strong></div><div class="sfu-stat"><span>{{ __('student_follow_up_admin.completed_contexts') }}</span><strong>{{ $teacherSummary['completed'] }}</strong></div><div class="sfu-stat"><span>{{ __('student_follow_up_admin.incomplete_contexts') }}</span><strong>{{ $teacherSummary['incomplete'] }}</strong></div><div class="sfu-stat"><span>{{ __('student_follow_up_admin.observations') }}</span><strong>{{ $teacherSummary['observations'] }}</strong></div></div>

    <h4 class="sfu-section-title">{{ __('student_follow_up_admin.assigned_classes') }}</h4>
    <div class="sfu-card-grid">@forelse($classGroups as $class)<a class="sfu-nav-card {{ $filters['class_id']==$class->id?'is-active':'' }}" href="{{ route('admin.student_follow_ups.teacher',['teacher'=>$teacher->id,'month'=>$month,'class_id'=>$class->id]) }}"><strong>{{ $class->name }}</strong><span>{{ $class->sections }} {{ __('student_follow_up_admin.assigned_sections') }}</span><span>{{ $class->students }} {{ __('student_follow_up_admin.student') }}</span><span>{{ $class->observations }} {{ __('student_follow_up_admin.observations') }}</span></a>@empty<div class="sfu-empty">{{ __('student_follow_up_admin.empty_text') }}</div>@endforelse</div>

    @if($filters['class_id'])<h4 class="sfu-section-title">{{ __('student_follow_up_admin.assigned_sections') }}</h4><div class="sfu-card-grid">@foreach($sectionGroups as $section)<a class="sfu-nav-card {{ $filters['room_id']==$section->id?'is-active':'' }}" href="{{ route('admin.student_follow_ups.teacher',['teacher'=>$teacher->id,'month'=>$month,'class_id'=>$section->class_id,'room_id'=>$section->id]) }}"><strong>{{ $section->name }}</strong><span>{{ $section->students }} {{ __('student_follow_up_admin.student') }}</span><span>{{ $section->lessons->implode('، ') }}</span><span>{{ $section->observations }} {{ __('student_follow_up_admin.observations') }}</span></a>@endforeach</div>@endif

    @if($filters['room_id'])
    <form class="sfu-filters sfu-detail-filters" method="get"><input type="hidden" name="month" value="{{ $month }}"><input type="hidden" name="class_id" value="{{ $filters['class_id'] }}"><input type="hidden" name="room_id" value="{{ $filters['room_id'] }}"><div class="sfu-field"><label>{{ __('student_follow_up_admin.student') }}</label><input class="form-control" name="search" value="{{ $filters['search'] }}" placeholder="{{ __('student_follow_up_admin.search_student') }}"></div><div class="sfu-field"><label>{{ __('student_follow_up_admin.subject') }}</label><select name="lesson_id"><option value="">{{ __('student_follow_up_admin.choose_subject') }}</option>@foreach($lessons as $lesson)<option value="{{ $lesson->id }}" {{ $filters['lesson_id']==$lesson->id?'selected':'' }}>{{ $lesson->name }}</option>@endforeach</select></div><div class="sfu-field"><label>{{ __('student_follow_up_admin.status') }}</label><select name="status"><option value="">{{ __('student_follow_up_admin.all') }}</option><option value="completed" {{ $filters['status']==='completed'?'selected':'' }}>{{ __('student_follow_up_admin.completed') }}</option><option value="missing_first" {{ in_array($filters['status'],['missing_first','missing_second'])?'selected':'' }}>{{ __('student_follow_up_admin.due_gaps') }}</option><option value="no_follow_up" {{ $filters['status']==='no_follow_up'?'selected':'' }}>{{ __('student_follow_up_admin.no_follow_up') }}</option></select></div><div class="sfu-filter-action"><button class="btn btn-primary">{{ __('student_follow_up_admin.apply') }}</button></div></form>
    @if($filters['lesson_id'] || $lessons->count()===1)
    <div class="sfu-table-card"><div class="sfu-table-wrap"><table class="table sfu-table"><thead><tr><th>{{ __('student_follow_up_admin.student') }}</th><th>{{ __('student_follow_up_admin.first_half') }}</th><th>{{ __('student_follow_up_admin.second_half') }}</th><th>{{ __('student_follow_up_admin.status') }}</th><th>{{ __('student_follow_up_admin.observations') }}</th><th>{{ __('student_follow_up_admin.inspect') }}</th></tr></thead><tbody>@forelse($rows as $row)<tr><td class="sfu-person">{{ $row->student_name }}</td><td>@include('admin.student_follow_ups._badge',['status'=>$row->half_one_status])</td><td>@include('admin.student_follow_ups._badge',['status'=>$row->half_two_status])</td><td>@include('admin.student_follow_ups._badge',['status'=>$row->monthly_status])</td><td>{{ $row->observation_count }}</td><td><div class="sfu-actions"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.student_follow_ups.observations',['teacher_id'=>$row->teacher_id,'student_id'=>$row->student_id,'lesson_id'=>$row->lesson_id,'room_id'=>$row->room_id,'month'=>$month]) }}">{{ __('student_follow_up_admin.inspect') }}</a><button type="button" class="btn btn-sm btn-primary js-sfu-add" data-url="{{ route('admin.student_follow_ups.store_on_behalf',['teacher'=>$row->teacher_id,'student'=>$row->student_id]) }}" data-assignment="{{ $row->assignment_id }}" data-teacher="{{ $row->teacher_name }}" data-student="{{ $row->student_name }}" data-class="{{ $row->class_name }}" data-room="{{ $row->room_name }}" data-lesson="{{ $row->lesson_name }}">{{ __('student_follow_up_admin.add_follow_up') }}</button></div></td></tr>@empty<tr><td colspan="6" class="sfu-empty">{{ __('student_follow_up_admin.empty_text') }}</td></tr>@endforelse</tbody></table></div></div>
    @else<div class="sfu-empty"><h4>{{ __('student_follow_up_admin.choose_subject') }}</h4></div>@endif
    @elseif($filters['class_id'])<div class="sfu-empty"><h4>{{ __('student_follow_up_admin.choose_section') }}</h4></div>@else<div class="sfu-empty"><h4>{{ __('student_follow_up_admin.choose_class') }}</h4></div>@endif
</div></div>

<div class="modal fade sfu-modal" id="sfuAdminAddModal" tabindex="-1" role="dialog" aria-labelledby="sfuAdminAddTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered" role="document"><div class="modal-content"><form id="sfuAdminAddForm" method="post">@csrf<input type="hidden" name="assignment_id" id="sfuAssignment"><input type="hidden" name="month" value="{{ $month }}"><input type="hidden" name="search" value="{{ $filters['search'] }}"><div class="modal-header"><div><h5 class="modal-title" id="sfuAdminAddTitle">{{ __('student_follow_up_admin.add_follow_up') }}</h5><p>تسجل أكاديمياً باسم المدرس، مع حفظ منفذ العملية من الإدارة.</p></div><button type="button" class="close" data-dismiss="modal" aria-label="إغلاق"><span aria-hidden="true">&times;</span></button></div><div class="modal-body"><div class="sfu-context-grid"><div><span>{{ __('student_follow_up_admin.teacher') }}</span><strong id="sfuTeacher"></strong></div><div><span>{{ __('student_follow_up_admin.student') }}</span><strong id="sfuStudent"></strong></div><div><span>{{ __('student_follow_up_admin.class') }}</span><strong id="sfuClass"></strong></div><div><span>{{ __('student_follow_up_admin.section') }}</span><strong id="sfuRoom"></strong></div><div class="wide"><span>{{ __('student_follow_up_admin.subject') }}</span><strong id="sfuLesson"></strong></div></div><div class="form-group"><label>{{ __('student_follow_up_admin.level') }}</label><select class="form-control" name="level"><option value="">{{ __('student_follow_up_admin.choose_level') }}</option>@foreach(\App\StudentFollowUp::LEVELS as $level)<option value="{{ $level }}">{{ __('student_follow_up.levels.'.$level) }}</option>@endforeach</select></div><div class="form-group"><label>{{ __('student_follow_up_admin.note') }}</label><textarea class="form-control" name="note" rows="5" maxlength="1000"></textarea><small class="text-muted">{{ __('student_follow_up_admin.content_help') }}</small></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-dismiss="modal">{{ __('student_follow_up_admin.cancel') }}</button><button type="submit" class="btn btn-primary js-sfu-submit">{{ __('student_follow_up_admin.save_follow_up') }}</button></div></form></div></div></div>
@endsection
@section('js')<script>$(document).on('click','.js-sfu-add',function(){var b=$(this),f=$('#sfuAdminAddForm');f.attr('action',b.data('url'));$('#sfuAssignment').val(b.data('assignment'));$('#sfuTeacher').text(b.data('teacher'));$('#sfuStudent').text(b.data('student'));$('#sfuClass').text(b.data('class'));$('#sfuRoom').text(b.data('room'));$('#sfuLesson').text(b.data('lesson'));$('#sfuAdminAddModal').modal('show');});$('#sfuAdminAddForm').on('submit',function(){var b=$(this).find('.js-sfu-submit');b.prop('disabled',true).text('جارٍ الحفظ...');});</script>@endsection
